# Generated by Django 2.1.4 on 2018-12-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_performer',
            field=models.BooleanField(default=False, verbose_name='Исполнитель ?'),
        ),
    ]
