# Generated by Django 2.1.4 on 2018-12-28 14:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 28, 14, 55, 11, 31922, tzinfo=utc)),
        ),
    ]
