# Generated by Django 2.1.4 on 2018-12-28 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_pp', models.IntegerField(blank=True, default=1, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('info', models.TextField(blank=True, default='', null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'verbose_name': 'Свойство\\Товар',
                'verbose_name_plural': 'Свойства\\Товары',
            },
        ),
        migrations.CreateModel(
            name='MainCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_pp', models.IntegerField(blank=True, default=1, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('discount', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('info', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'verbose_name': 'Главная категория',
                'verbose_name_plural': 'Главные категории',
            },
        ),
        migrations.CreateModel(
            name='SubCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_pp', models.IntegerField(blank=True, default=1, null=True)),
                ('block', models.IntegerField(blank=True, default=0, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('postobrab', models.BooleanField(blank=True, default=False, null=True)),
                ('action_summ', models.BooleanField(blank=True, default=False, null=True)),
                ('info', models.TextField(blank=True, default='', null=True)),
                ('postobrab_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('main_cat', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.MainCat')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='sub_cat',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.SubCat'),
        ),
    ]
